name = "qr"
main = "./src/handler.ts"
compatibility_date = "2022-02-25"

kv_namespaces = [
    { binding = "KV_STORAGE", id = "9f7fd0d25df4437e9651349aa9880eec" },
]

[vars]
EDIT_TOKEN = "STI2"
R2_BUCKET_DOMAIN = "qr-storage.pgerry.com"

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'qr-epfl'
