name = "qr"
type = "javascript"
main = "./src/handler.ts"
workers_dev = true
compatibility_date = "2022-02-25"

kv_namespaces = [
    { binding = "KV_STORAGE", id = "9f7fd0d25df4437e9651349aa9880eec" },
]

[vars]
EDIT_TOKEN = "STI2"

[build]
command = "npm install && npm run build"

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'qr-epfl'
